### ISSUE TITLE
module 'jointfunc_vcg.data' has no attribute 'nonrising'

### ISSUE THREAD

**Issue by RayX47** [liran-funaro/jointfunc-vcg#1]
Excuse me, it's me again.

I have installed vec,vec-vcg,cloudsim. 
And something wrong in the second cell of the notebook.
`sd = data.nonrising.generate_data_item(0)`

**AttributeError: module 'jointfunc_vcg.data' has no attribute 'nonrising'**

I try to find **'nonrising'** , but I can't find it.
Did I miss something to install?

Thank you for your reply.

**Comment by liran-funaro** [comment]
Hi.

Thanks for raising this issue.
I think you are the first user of this package (that is not me) so you find all the small issues I left behind.
Please continue to inform me about any issue you might find.

Specifically, this should be fixed by using `data.non_increasing` instead.
I'll fix it once I will be next to a computer.

Thanks!

**Comment by RayX47** [comment]
Yes, I'm a newcommer about the auction in Cloud. And it's my honor to read your paper. So I want to read the code to help me understand your paper further.

To be honest, there are lots of errors in the code. And I'm trying to learn by fixing the code.

By the way, I find another new **ERROR**:jointfunc_vcg miss package 'sim' However, I can't copy 'sim' to use in the project 'stochastic-allocation'

Your help will mean a lot!

**Comment by liran-funaro** [comment]
Thanks.

> `sd = data.nonrising.generate_data_item(0)`

I fixed the notebook.

> To be honest, there are lots of errors in the code. And I'm trying to learn by fixing the code.

Feel free to publish pull-requests on errors you find. 

> By the way, I find another new ERROR:jointfunc_vcg miss package 'sim' However, I can't copy 'sim' to use in the project 'stochastic-allocation'

Can you elaborate? Where is it used?

**Comment by RayX47** [comment]
create datasets.ipynb

display(***sim**.print_simulations_status_joined(show_finished_count=9, progress_columns=3))

Thank U very much.

**Comment by liran-funaro** [comment]
I fixed this issue and other similar issues I found in this notebook.
Thank you for your contribution. Please keep opening new issues/PRs for problems you encounter.
